version: "3.7"
services:
  back:
    image: bitclaw/quotes-back:v1
    ports:
      - "3000:3000"
    networks:
      - myapp

  data:
    image: bitclaw/quotes-data:v1
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "mydatabase"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - myapp

networks:
  myapp: